import { ClerkProvider, SignedIn } from "@clerk/nextjs";
import type { Metadata } from "next";
import Sidebar from "./components/Sidebar";
import ThemeWrapper from "./components/ThemeWrapper";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body>
          <ThemeWrapper>
            <div className="flex w-full">
              <SignedIn>
                <Sidebar />
              </SignedIn>
              <main className="flex-1">{children}</main>
            </div>
          </ThemeWrapper>
        </body>
      </ClerkProvider>
    </html>
  );
}
